#!/usr/bin/env bash

# Exit on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands before executing them, by default to stderr.
set -x

readonly BIN_PATH='./bin/example'
readonly CC='gcc'

"${CC}" arithmetic.c main.c -o "${BIN_PATH}"

"${BIN_PATH}"
