#!/usr/bin/env bash

# Exit on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands before executing them, by default to stderr.
set -x

readonly BIN_DIR='./bin'
readonly BIN_PATH="${BIN_DIR}/example"
readonly CC='zig cc'

mkdir -p "${BIN_DIR}"

${CC} arithmetic.c main.c -o "${BIN_PATH}"

"${BIN_PATH}"
